- name: Upgrade packages
  ansible.builtin.include_tasks: upgrade_packages.yml

- name: Install CLI tools
  ansible.builtin.include_tasks: install_cli_tools.yml

- name: Install applications
  ansible.builtin.include_tasks: install_applications.yml

- name: Install fonts
  ansible.builtin.include_tasks: install_fonts.yml

- name: Configure default shell
  ansible.builtin.include_tasks: configure_default_shell.yml
