- name: Update package manager cache
  ansible.builtin.dnf:
    update_cache: yes
  become: yes

## INSTALL SOFTWARE

# COPRs
- name: Enable startship COPR
  community.general.copr:
    name: atim/starship
    state: enabled
  become: yes

- name: Enable Ghostty COPR
  community.general.copr:
    name: pgdev/ghostty
    state: enabled
  become: yes

# Tools and utilities
- name: Install command line packages
  ansible.builtin.dnf:
    name:
      - fastfetch
      - fzf
      - git
      - helix
      - starship
      - stow
      - zoxide
    state: latest
  become: yes

- name: Install terminal
  dnf:
    name: ghostty
    enablerepo: pgdev/ghostty
    state: latest
  become: yes

# Productivity
- name: Install notes manager
  community.general.flatpak:
    name: md.obsidian.Obsidian
    state: latest
  become: yes

- name: Install text editor
  community.general.flatpak:
    name: com.visualstudio.code
    state: latest
  become: yes

- name: Install web browser
  community.general.flatpak:
    name: 
      - com.brave.Browser
    state: latest
  become: yes

# Communication
- name: Install communication tools
  community.general.flatpak:
    name: com.discordapp.Discord
    state: latest
  become: yes

# Entertainment
- name: Install game store and launcher
  ansible.builtin.dnf:
    name: steam
    state: present
  become: yes

- name: Install music player
  community.general.flatpak:
    name: 
    - com.spotify.Client
    state: latest
  become: yes

- name: Install video player
  community.general.flatpak:
    name: org.videolan.VLC
    state: latest
  become: yes

## Dotfile management

- name: Apply dotfiles
  ansible.builtin.include_role:
    name: dotfiles
