- name: Update package manager cache
  ansible.builtin.dnf:
    update_cache: yes
  become: yes

## INSTALL SOFTWARE

# Tools and utilities
- name: Install command line packages
  ansible.builtin.dnf:
    name:
      - fastfetch
      - git
      - helix
      - tmux
      - zoxide
    state: latest
  become: yes

- name: Install secrets manager
  block:
    - name: Add the key for the 1Password yum repository
      rpm_key:
        key: https://downloads.1password.com/linux/keys/1password.asc
        state: present
      become: yes
    - name: Add the 1Password yum repository
      copy:
        content: |
          [1password]
          name=1Password Stable Channel
          baseurl=https://downloads.1password.com/linux/rpm/stable/$basearch
          enabled=1
          gpgcheck=1
          repo_gpgcheck=1
          gpgkey=https://downloads.1password.com/linux/keys/1password.asc
        dest: /etc/yum.repos.d/1password.repo
      become: yes
    - name: Install 1Password
      package:
        name: 1password
        state: latest
      become: yes

- name: Install terminal
  dnf:
    name: ghostty
    enablerepo: pgdev/ghostty
    state: present
  become: yes

# Productivity
- name: Install launcher
  ansible.builtin.dnf:
    name: ulauncher
    state: latest
  become: yes

- name: Install notes manager
  community.general.flatpak:
    name: md.obsidian.Obsidian
    state: latest
  become: yes

- name: Install text editor
  community.general.flatpak:
    name: com.visualstudio.code
    state: latest
  become: yes

- name: Install web browser
  community.general.flatpak:
    name: 
      - org.mozilla.firefox
      - app.zen_browser.zen
    state: latest
  become: yes

# Communication
- name: Install communication tools
  community.general.flatpak:
    name: com.discordapp.Discord
    state: latest
  become: yes

# Entertainment
- name: Install game store and launcher
  ansible.builtin.dnf:
    name: steam
    state: present
  become: yes

- name: Install music player
  community.general.flatpak:
    name: 
    - com.spotify.Client
    - com.mastermindzh.tidal-hifi
    state: latest
  become: yes

- name: Install video player
  community.general.flatpak:
    name: org.videolan.VLC
    state: latest
  become: yes

## REMOVE UNUSED SOFTWARE.
- name: Remove unneeded software
  ansible.builtin.dnf:
    name:
     - firefox
     - totem
     - vlc
    state: absent
  become: yes
