- name: Update package manager cache
  ansible.builtin.dnf:
    update_cache: yes
  become: yes

## INSTALL SOFTWARE

# COPRs
- name: Enable startship COPR
  community.general.copr:
    name: atim/starship
    state: enabled
  become: yes

- name: Enable Ghostty COPR
  community.general.copr:
    name: pgdev/ghostty
    state: enabled
  become: yes

# Tools and utilities
- name: Install command line packages
  ansible.builtin.dnf:
    name:
      - fastfetch
      - fzf
      - git
      - helix
      - neovim
      - starship
      - stow
      - zsh
      - zoxide
    state: latest
  become: yes

- name: Install terminal
  dnf:
    name: ghostty
    enablerepo: pgdev/ghostty
    state: latest
  become: yes

# Set default shell
- name: Get path to zsh
  command: which zsh
  register: zsh_path_result
  changed_when: false

- name: Set Zsh as default shell
  become: true
  user:
    name: "{{ lookup('env', 'USER') }}"
    shell: "{{ zsh_path_result.stdout }}"

# Productivity
- name: Install notes manager
  community.general.flatpak:
    name: md.obsidian.Obsidian
    state: latest
  become: yes

- name: Import Microsoft GPG key
  ansible.builtin.rpm_key:
    key: https://packages.microsoft.com/keys/microsoft.asc
    state: present
  become: yes

- name: Add Visual Studio Code repository
  ansible.builtin.yum_repository:
    name: code
    description: Visual Studio Code
    baseurl: https://packages.microsoft.com/yumrepos/vscode
    gpgcheck: yes
    gpgkey: https://packages.microsoft.com/keys/microsoft.asc
  become: yes

- name: Install text editor
  ansible.builtin.dnf:
    name: code
    state: latest
  become: yes

- name: Install web browser
  community.general.flatpak:
    name: 
      - com.brave.Browser
    state: latest
  become: yes

# Communication
- name: Install chat tools
  community.general.flatpak:
    name: com.discordapp.Discord
    state: latest
  become: yes

- name: Install email client
  community.general.flatpak:
    name: me.proton.Mail
    state: latest
  become: yes

# Entertainment
- name: Install game store and launcher
  ansible.builtin.dnf:
    name: steam
    state: present
  become: yes

- name: Install music player
  community.general.flatpak:
    name: 
    - com.spotify.Client
    state: latest
  become: yes

- name: Install video player
  community.general.flatpak:
    name: org.videolan.VLC
    state: latest
  become: yes

## System monitoring and resource management

- name: Install performance monitor
  ansible.builtin.dnf:
    name: goverlay
    state: latest
  become: yes

## Dotfile management

# LazyVim configuration
- name: Check if Neovim config exists
  ansible.builtin.stat:
    path: ~/.config/nvim
  register: nvim_config
  become: no

- name: Clone LazyVim starter configuration
  ansible.builtin.git:
    repo: https://github.com/LazyVim/starter
    dest: ~/.config/nvim
  become: no
  when: not nvim_config.stat.exists

- name: Remove LazyVim starter .git directory
  ansible.builtin.file:
    path: ~/.config/nvim/.git
    state: absent
  become: no
  when: not nvim_config.stat.exists

- name: Apply dotfiles
  ansible.builtin.include_role:
    name: dotfiles
