---
- name: Get path to zsh
  command: which zsh
  register: zsh_path_result
  changed_when: false

- name: Set Zsh as default shell
  become: yes
  user:
    name: "{{ lookup('env', 'USER') }}"
    shell: "{{ zsh_path_result.stdout }}"