---
- name: Install applications via Homebrew Cask (macOS)
  community.general.homebrew_cask:
    name: "{{ item[current_os].package }}"
    state: latest
    greedy: yes
  loop: "{{ applications }}"
  when: 
    - current_os == 'macos'
    - item[current_os].type == 'homebrew_cask'
  loop_control:
    label: "{{ item.name }}"

- name: Install applications via DNF (Fedora)
  ansible.builtin.dnf:
    name: "{{ item[current_os].package }}"
    state: latest
  become: yes
  loop: "{{ applications }}"
  when: 
    - current_os == 'fedora'
    - item[current_os].type == 'dnf'
    - item[current_os].repo_setup is not defined
    - item[current_os].copr is not defined
  loop_control:
    label: "{{ item.name }}"

- name: Install applications from COPR (Fedora)
  ansible.builtin.dnf:
    name: "{{ item[current_os].package }}"
    enablerepo: "{{ item[current_os].copr }}"
    state: latest
  become: yes
  loop: "{{ applications }}"
  when: 
    - current_os == 'fedora'
    - item[current_os].type == 'dnf'
    - item[current_os].copr is defined
  loop_control:
    label: "{{ item.name }}"

- name: Install applications with repository setup (Fedora)
  ansible.builtin.dnf:
    name: "{{ item[current_os].package }}"
    state: latest
  become: yes
  loop: "{{ applications }}"
  when: 
    - current_os == 'fedora'
    - item[current_os].type == 'dnf'
    - item[current_os].repo_setup is defined
  loop_control:
    label: "{{ item.name }}"

- name: Install applications via Flatpak (Fedora)
  community.general.flatpak:
    name: "{{ item[current_os].package }}"
    state: latest
  become: yes
  loop: "{{ applications }}"
  when: 
    - current_os == 'fedora'
    - item[current_os].type == 'flatpak'
  loop_control:
    label: "{{ item.name }}"