---
- name: Include variable files
  include_vars: "{{ item }}"
  with_fileglob:
    - "../vars/*.yml"

- name: Set OS-specific variables
  set_fact:
    current_os: "{{ 'macos' if ansible_os_family == 'Darwin' else 'fedora' if ansible_os_family == 'RedHat' else 'arch' if ansible_os_family == 'Archlinux' else 'unknown' }}"

- name: Fail if unsupported OS
  fail:
    msg: "Unsupported OS family: {{ ansible_os_family }}"
  when: current_os == 'unknown'

# Package manager updates
- include_tasks: update_package_managers.yml

# Setup repositories and COPRs
- include_tasks: setup_repositories.yml
  when: current_os == 'fedora'

# Install software by category
- include_tasks: install_packages.yml
  vars:
    packages: "{{ cli_tools }}"
    package_type: "CLI tools"

- include_tasks: install_packages.yml
  vars:
    packages: "{{ applications }}"
    package_type: "applications"

- include_tasks: install_fonts.yml

# Post-installation tasks
- include_tasks: configure_shell.yml
