cli_tools:
  # AI Tools
  - name: claude-code
    arch:
      source: paru
      name: claude-code
    fedora:
      source: manual # Manually install: https://docs.anthropic.com/en/docs/claude-code/overview#get-started-in-30-seconds

  # Development Tools
  - name: ansible-lint
    arch:
      source: pacman
      name: ansible-lint
    fedora:
      source: dnf
      name: python3-ansible-lint.noarch
    macos:
      source: brew
  - name: git
    macos:
      source: brew
  - name: neovim
    arch:
      source: pacman
    fedora:
      source: dnf
    macos:
      source: brew
  - name: volta
    arch:
      source: script
      script_name: install-volta.sh
      creates: "{{ ansible_env.HOME }}/.volta"
    fedora:
      source: script
      script_name: install-volta.sh
      creates: "{{ ansible_env.HOME }}/.volta"
    macos:
      source: script
      script_name: install-volta.sh
      creates: "{{ ansible_env.HOME }}/.volta"

  # File & Directory Tools
  - name: fzf
    arch:
      source: pacman
    fedora:
      source: dnf
    macos:
      source: brew
  - name: stow
    arch:
      source: pacman
    fedora:
      source: dnf
    macos:
      source: brew
  - name: zoxide
    arch:
      source: pacman
    fedora:
      source: dnf
    macos:
      source: brew

  # Shell & Terminal Enhancement
  - name: atuin
    arch:
      source: pacman
    fedora:
      source: dnf
    macos:
      source: brew
  - name: starship
    arch:
      source: pacman
    fedora:
      source: dnf
    macos:
      source: brew
  - name: zsh
    arch:
      source: pacman
    fedora:
      source: dnf

  # System Information
  - name: fastfetch
    arch:
      source: pacman
    fedora:
      source: dnf
    macos:
      source: brew
