cli_tools:
  # System dependencies
  - name: xdg-desktop-portal # Required for some Flatpak apps to work properly.
    arch:
      source: pacman
  - name: xdg-desktop-portal-kde # Assumes KDE.
    arch:
      source: pacman

  # AI Tools
  - name: claude-code
    arch:
      source: paru
      name: claude-code
    fedora:
      source: manual # Manually install: https://docs.anthropic.com/en/docs/claude-code/overview#get-started-in-30-seconds

  # Development Tools
  - name: git
    macos:
      source: brew
  - name: neovim
    arch:
      source: pacman
    fedora:
      source: dnf
    macos:
      source: brew
  - name: volta
    arch:
      source: script
      script_name: install-volta.sh
      creates: "{{ ansible_env.HOME }}/.volta"
    fedora:
      source: script
      script_name: install-volta.sh
      creates: "{{ ansible_env.HOME }}/.volta"
    macos:
      source: script
      script_name: install-volta.sh
      creates: "{{ ansible_env.HOME }}/.volta"

  # File & Directory Tools
  - name: fzf
    arch:
      source: pacman
    fedora:
      source: dnf
    macos:
      source: brew
  - name: stow
    arch:
      source: pacman
    fedora:
      source: dnf
    macos:
      source: brew
  - name: zoxide
    arch:
      source: pacman
    fedora:
      source: dnf
    macos:
      source: brew

  # Shell & Terminal Enhancement
  - name: atuin
    arch:
      source: pacman
    fedora:
      source: dnf
    macos:
      source: brew
  - name: starship
    arch:
      source: pacman
    fedora:
      source: dnf
    macos:
      source: brew
  - name: zsh
    arch:
      source: pacman
    fedora:
      source: dnf

  # System Information
  - name: fastfetch
    arch:
      source: pacman
    fedora:
      source: dnf
    macos:
      source: brew
