fonts:
  - name: fire-code-nerd-font
    arch:
      source: pacman
      name: ttf-firacode-nerd
    fedora:
      source: manual # Manually install: https://www.nerdfonts.com/font-downloads
    macos:
      source: brew
      name: font-fira-code-nerd-font
