---
- name: Get path to zsh
  command: which zsh
  register: zsh_path_result
  changed_when: false

- name: Set Zsh as default shell
  become: true
  user:
    name: "{{ ansible_user_id }}"
    shell: "{{ zsh_path_result.stdout }}"
