- name: Install command line tools via Homebrew
  loop: "{{ cli_tools }}"
  when:
    - item.macos is defined
    - item.macos.source == 'brew'
  community.general.homebrew:
    name: "{{ item.macos.name | default(item.name) }}"
    state: latest
  become: false

- name: Install command line tools via script
  loop: "{{ cli_tools }}"
  when:
    - item.macos is defined
    - item.macos.source == 'script'
  ansible.builtin.script:
    cmd: "{{ item.macos.script_name }}"
    creates: "{{ item.macos.creates }}"
