- name: Install applications via Homebrew
  loop: "{{ applications }}"
  when:
    - item.macos is defined
    - item.macos.source == 'brew'
  community.general.homebrew_cask:
    name: "{{ item.macos.name | default(item.name) }}"
    state: latest
    greedy: yes
  become: no
