- name: Update package manager cache
  community.general.homebrew:
    update_homebrew: yes

## INSTALL SOFTWARE

# Tools and utilities
- name: Install command line packages
  community.general.homebrew:
    name:
      - fastfetch
      - fzf
      - git
      - helix
      - neovim
      - starship
      - stow
      - zoxide
    state: latest

- name: Install secrets manager
  community.general.homebrew_cask:
    name: 1password
    state: latest
    greedy: yes

- name: Install terminal
  community.general.homebrew_cask:
    name: ghostty
    state: latest
    greedy: yes

# Productivity
- name: Install notes manager
  community.general.homebrew_cask:
    name: obsidian
    state: latest
    greedy: yes

- name: Install text editor
  community.general.homebrew_cask:
    name: visual-studio-code
    state: latest
    greedy: yes

- name: Install toto list manager
  community.general.homebrew_cask:
    name: ticktick
    state: latest
    greedy: yes

- name: Install window manager
  community.general.homebrew_cask:
    name: rectangle
    state: latest
    greedy: yes

- name: Install web browser
  community.general.homebrew_cask:
    name: 
      - brave-browser
      - firefox
    state: latest
    greedy: yes

# Communication
- name: Install communication tools
  community.general.homebrew_cask:
    name: discord
    state: latest
    greedy: yes

# Entertainment
- name: Install music player
  community.general.homebrew_cask:
    name: 
    - spotify
    state: latest
    greedy: yes

- name: Install video player
  community.general.homebrew_cask:
    name: vlc
    state: latest
    greedy: yes

# Fonts
- name: Install fonts
  community.general.homebrew_cask:
    name: font-hack-nerd-font
    state: latest

# LazyVim configuration
- name: Clone LazyVim starter configuration
  ansible.builtin.git:
    repo: https://github.com/LazyVim/starter
    dest: ~/.config/nvim
    force: yes
  become: no

- name: Remove LazyVim starter .git directory
  ansible.builtin.file:
    path: ~/.config/nvim/.git
    state: absent
  become: no

- name: Apply dotfiles
  ansible.builtin.include_role:
    name: dotfiles
