- name: Install command line tools via Pacman
  loop: "{{ cli_tools }}"
  when:
    - item.arch is defined
    - item.arch.source == 'pacman'
  community.general.pacman:
    name: "{{ item.arch.name | default(item.name) }}"
    state: present
  become: true

- name: Install command line tools via Paru
  loop: "{{ cli_tools }}"
  when:
    - item.arch is defined
    - item.arch.source == 'paru'
  kewlfft.aur.aur:
    use: paru
    name: "{{ item.arch.name | default(item.name) }}"
    state: present # Paru packages will be updated holistically in a separate task.
  become: true
  become_user: aur_builder

- name: Install command line tools via script
  loop: "{{ cli_tools }}"
  when:
    - item.arch is defined
    - item.arch.source == 'script'
  ansible.builtin.shell: |
    set -o pipefail
    if ! command -v {{ item.name }} &> /dev/null; then
      curl -sSL {{ item.arch.url }} | bash
    fi
  args:
    creates: "{{ item.arch.creates }}"
