- name: Install applications via native package manager
  loop: "{{ applications }}"
  when:
    - item.arch is defined
    - item.arch.source in ['pacman', 'paru'] # Note - 'paru' is unlikely to properly function at this time.
  community.general.pacman:
    executable: "/usr/bin/{{ item.arch.source }}"
    name: "{{ item.arch.name | default(item.name) }}"
    state: present # Arch and AUR packages will be updated holistically in a separate task.
  become: yes

- name: Install applications via Flatpak
  loop: "{{ applications }}"
  when:
    - item.arch is defined
    - item.arch.source == 'flatpak'
  community.general.flatpak:
    name: "{{ item.arch.name | default(item.name) }}"
    state: latest # Flatpak packages will be updated piecemeal.
  become: no
