- name: Install applications via Pacman
  loop: "{{ applications }}"
  when:
    - item.arch is defined
    - item.arch.source == 'pacman'
  community.general.pacman:
    name: "{{ item.arch.name | default(item.name) }}"
    state: present # Arch Pacman packages will be updated holistically in a separate task.
  become: yes

- name: Install applications via Paru
  loop: "{{ applications }}"
  when:
    - item.arch is defined
    - item.arch.source == 'paru'
  kewlfft.aur.aur:
    use: paru
    name: "{{ item.arch.name | default(item.name) }}"
    state: present # Paru packages will be updated holistically in a separate task.
  become: yes
  become_user: "{{ ansible_user_id }}"

- name: Install applications via Flatpak
  loop: "{{ applications }}"
  when:
    - item.arch is defined
    - item.arch.source == 'flatpak'
  community.general.flatpak:
    name: "{{ item.arch.name | default(item.name) }}"
    state: latest # Flatpak packages will be updated piecemeal.
  become: no
