- name: Remove sudoers file for aur_builder user
  become: true
  ansible.builtin.file:
    path: /etc/sudoers.d/11-install-aur_builder
    state: absent

- name: Remove the aur_builder user
  become: true
  ansible.builtin.user:
    name: aur_builder
    state: absent
    remove: true
